PREFIX dcterms:<http://purl.org/dc/terms/>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX rinfo:<http://rinfo.lagrummet.se/taxo/2007/09/rinfo/pub#>

SELECT DISTINCT ?uri ?label
WHERE {
    GRAPH <urn:x-local:sfs> {
       { ?uri dcterms:subject <%(uri)s> .
         ?baseuri dcterms:title ?label .
         ?uri dcterms:isPartOf ?x . ?x dcterms:isPartOf ?baseuri
       }
       UNION {
         ?uri dcterms:subject <%(uri)s> .
         ?baseuri dcterms:title ?label .
         ?uri dcterms:isPartOf ?x . ?x dcterms:isPartOf ?y . ?y dcterms:isPartOf ?baseuri
       }
       UNION {
         ?uri dcterms:subject <%(uri)s> .
         ?baseuri dcterms:title ?label .
         ?uri dcterms:isPartOf ?x . ?x dcterms:isPartOf ?y . ?x dcterms:isPartOf ?z . ?z dcterms:isPartOf ?baseuri
       }
       UNION {
         ?uri dcterms:subject <%(uri)s> .
         ?baseuri dcterms:title ?label .
         ?uri dcterms:isPartOf ?x . ?x dcterms:isPartOf ?y . ?x dcterms:isPartOf ?z . ?z dcterms:isPartOf ?w . ?w dcterms:isPartOf ?baseuri
       }
    }
}

