PREFIX dcterms:<http://purl.org/dc/terms/>
PREFIX rpubl:<http://rinfo.lagrummet.se/ns/2008/11/rinfo/publ#>

SELECT ?change ?lagrum
WHERE { ?change rpubl:ersatter ?lagrum.
        FILTER(STRSTARTS(STR(?lagrum), "%(uri)s")) 
}
